2025-04-19 06:21:27,157 : INFO : Start of Prediction
2025-04-19 06:21:27,159 : INFO : run_id:2025-04-19_062127_254042067
2025-04-19 06:21:27,159 : INFO : Start of Data Load, validation and transformation
2025-04-19 06:21:27,159 : INFO : Start of Archiving Old Rejected Files...
2025-04-19 06:21:27,164 : INFO : End of Archiving Old Rejected Files...
2025-04-19 06:21:27,164 : INFO : Start of Archiving Old Validated Files...
2025-04-19 06:21:27,167 : INFO : End of Archiving Old Validated Files...
2025-04-19 06:21:27,167 : INFO : Start of Archiving Old Processed Files...
2025-04-19 06:21:27,168 : INFO : End of Archiving Old Processed Files...
2025-04-19 06:21:27,168 : INFO : Start of Archiving Old Result Files...
2025-04-19 06:21:27,169 : INFO : End of Archiving Old Result Files...
2025-04-19 06:21:27,169 : INFO : Start of Reading values From Schema...
2025-04-19 06:21:27,170 : INFO : End of Reading values From Schema...
2025-04-19 06:21:27,170 : INFO : Start of Validating Column Length...
2025-04-19 06:21:27,170 : INFO : End of Validating Column Length...
2025-04-19 06:21:27,170 : INFO : Start of Validating Missing Values...
2025-04-19 06:21:27,170 : INFO : End of Validating Missing Values...
2025-04-19 06:21:27,170 : INFO : Start of Replacing Missing Values with NULL...
2025-04-19 06:21:27,171 : INFO : End of Replacing Missing Values with NULL...
2025-04-19 06:21:27,171 : INFO : Start of Creating Table...
2025-04-19 06:21:27,172 : INFO : Opened prediction database successfully
2025-04-19 06:21:27,183 : INFO : CREATE TABLE prediction_raw_data_t column_name
2025-04-19 06:21:27,188 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,193 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,199 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,205 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,210 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,215 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,220 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,226 : INFO : ALTER TABLE prediction_raw_data_t ADD COLUMN
2025-04-19 06:21:27,226 : INFO : End of Creating Table...
2025-04-19 06:21:27,229 : INFO : Opened prediction database successfully
2025-04-19 06:21:27,229 : INFO : Start of Inserting Data into Table...
2025-04-19 06:21:27,229 : INFO : End of Inserting Data into Table...
2025-04-19 06:21:27,230 : INFO : Start of Exporting Data into CSV...
2025-04-19 06:21:27,230 : INFO : Opened prediction database successfully
2025-04-19 06:21:27,232 : INFO : End of Exporting Data into CSV...
2025-04-19 06:21:27,233 : INFO : Start of Moving Processed Files...
2025-04-19 06:21:27,233 : INFO : End of Moving Processed Files...
2025-04-19 06:21:27,234 : INFO : End of Data Load, validation and transformation
2025-04-19 06:21:27,234 : INFO : Start of Preprocessing...
2025-04-19 06:21:27,234 : INFO : Start of reading dataset...
2025-04-19 06:21:27,239 : INFO : End of reading dataset...
2025-04-19 06:21:27,239 : INFO : Start of feature encoding...
2025-04-19 06:21:27,253 : INFO : End of feature encoding...
2025-04-19 06:21:27,254 : INFO : Start of Droping Columns...
2025-04-19 06:21:27,254 : INFO : End of Droping Columns...
2025-04-19 06:21:27,255 : INFO : Start of finding missing values...
2025-04-19 06:21:27,255 : INFO : End of finding missing values...
2025-04-19 06:21:27,255 : INFO : Start of building final predictset...
2025-04-19 06:21:27,257 : INFO : End of building final predictset...
2025-04-19 06:21:27,257 : INFO : End of Preprocessing...
2025-04-19 06:21:27,257 : INFO : Start of Load Model
2025-04-19 06:21:27,259 : ERROR : Exception raised while Loading Model: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'
2025-04-19 06:21:27,260 : ERROR : Unsuccessful End of Prediction
Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 79, in load_model
    with open('apps/models/' + file_name + '/' + file_name + '.sav','rb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'apps/models/KMeans/KMeans.sav'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\prediction\predict_model.py", line 58, in batch_predict_from_model
    kmeans = self.fileOperation.load_model('KMeans')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NISHANT SINGH\PycharmProjects\EmployeeRetention\apps\core\file_operation.py", line 85, in load_model
    raise Exception()
Exception
